GET http://localhost:8000/api/article/home
Accept: application/json

###
GET http://localhost:8000/api/article/block/1/0
Accept: application/json

###
POST http://localhost:8000/api/article
Content-Type: application/json

{
    "header": "Demo",
    "content": "Dick",
    "email": "mxr@qq.com",
    "blockId": "1"
}

###
GET http://localhost:8000/
Accept: application/json

###
GET http://localhost:8000/api/article/detail/1
Accept: application/json

###

PUT http://localhost:8000/api/article
Content-Type: application/json

{
    "header": "updated header",
    "content": "Penis",
    "id": 1
}

###